spring:
  mvc:
    view:
      prefix: /templates/

  datasource:
      url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  application:
    name: bootweb
master:
  datasource:   #主库
    url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

cluster:
  datasource:   #从库
      url: jdbc:mysql://rm-bp1e5wj1225x3b702o.mysql.rds.aliyuncs.com:3306/dbgirl_cluster?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: Khjk2017
      driverClassName: com.mysql.jdbc.Driver



mybatis:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mars.model
  configuration:
    map-underscore-to-camel-case: true


logging:
  config: classpath:logback-spring.xml
