spring:
  mvc:
    view:
      prefix: /templates/
  datasource:
    url: jdbc:mysql://localhost:3306/dbgirl?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mars.model
  configuration:
    map-underscore-to-camel-case: true